REGLES DE PASSAGE OO (DAIGRAMME DE CLASSE UML) VERS SCHEMA RELATIONNEL DE LA BASE DE DONNEES

R1 : classe => table
attributs => colonnes 
identifiant => cle primaire

R2 : 
CAS D'UNE RELATION : 1<->* : CLE PRIMAIRE DE LA TABLE COTE 1 DEVIENT CLE ETRANGERE DANS LA TABLE COTE *
R3
CASE D'UNE RELATION : *<-> * : LES  CLES PRIMAIRES DES TABLES DEVIENNENT DES CLES ETRANGERES DANS UNE NOUVELLE TABLE (PIVOT) 
LES DEUX CLES ETRAGERES CONSTITUENT LA CLES PRIMAIRE DE LA TABLE PIVOT
R4 : 
CASE D'UNE RELATION : *<-> *  AVEC UNE TABLE ASSOCIATION : LES  CLES PRIMAIRES DES TABLES DEVIENNENT DES CLES ETRANGERES DANS UNE NOUVELLE TABLE (PIVOT)
